Automatically switch difftype if other has files and the current one doesn't
M4tthewDE/contrast pull request #35
Opened 2023-08-22 07:38 UTC by NotNotQuinn

2023-08-22 07:45 UTC, M4tthewDE requested changes

2023-08-22 07:45 UTC, M4tthewDE commented on src/main.rs
> +                }
This should happen in UI code. I want to keep logic out of the message handling as much as possible.

2023-08-23 07:14 UTC, NotNotQuinn commented
I don't really like this solution. It "works", but you can't open changes that don't have files in them. This doesn't logistically create any problems but it removes a feeling of control when using the application. Read previous commit message for more information.

I have a few ideas for resolutions:
 - Place the diff type update logic in `Message::LoadDiff` or another `Message::*` (old)
 - Update the diff type every frame (current)
 - Add a control flag (`control_data.just_loaded_diff`) which is set in `Message::LoadDiff`
 - New method `MyApp::on_load_diff()` called in `Message::LoadDiff`

2023-08-23 08:05 UTC, M4tthewDE commented
As I see it, we only care about the initial selection, before the user has selected anything. The ui should display whatever is inside of the ControlData. I would add another function to MyApp, which is called when Message::LoadDiff is received.
Inside the function the AppData is created and the correct initial DiffType is computed.

2023-08-23 08:46 UTC, M4tthewDE commented on src/main.rs
> +                }
Pass the app_data from the Message directly to the function. That way you don't have to check inside of self.update_app_data() if it's not None.

2023-08-23 09:06 UTC, M4tthewDE approved these changes
LGTM

2023-08-23 09:07 UTC, merged